trigger:
  branches:
    include:
      - main  # Trigger pipeline when changes are pushed to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'UST DeliveryOps GenAI POC'  # Your Azure Subscription name
  appName: 'my-springboot-app'  # Name of your Azure App Service
  resourceGroup: 'my-resource-group'  # Your Azure Resource Group name
  publishProfile: 'my-publish-profile'  # Azure App Service publish profile
  javaVersion: '11'  # Set Java version

jobs:
- job: Build
  displayName: 'Build Spring Boot Application'
  steps:
  - task: Checkout@1
    displayName: 'Checkout source code from GitHub'
  
  - task: Maven@3
    displayName: 'Build with Maven'
    inputs:
      mavenPomFile: 'pom.xml'  # Path to your Maven pom.xml file
      goals: 'clean package'

- job: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: Build
  steps:
  - task: AzureWebApp@1
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: $(azureSubscription)  # Set in Azure DevOps
      appName: $(appName)  # Azure App Service name
      package: '$(Build.ArtifactStagingDirectory)/*.jar'  # Path to your packaged Spring Boot app (e.g., .jar file)
      publishProfile: $(publishProfile)  # Your Azure publish profile credentials (set this securely)
