pipeline:
  name: build
  identifier: build
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build and Deploy
        identifier: Build_And_Deploy
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: Checkout Code
                  identifier: Checkout_Code
                  type: ShellScript
                  spec:
                    shell: Bash
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "Cloning the  repo..."
                          rm -rf helloservice
                          git clone https://github.com/DatlaBharath/helloservice.git
                          cd helloservice
                          pwd
                          ls
                    executionTarget: {}
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  name: Build Project
                  identifier: Build_Project
                  type: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          cd helloservice
                          mvn clean install -DskipTests
              - step:
                  name: Build Docker Image
                  identifier: Build_Image
                  type: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          cd helloservice
                          docker build -t sakthisiddu1/helloservice:<+pipeline.sequenceId> .
              - step:
                  name: Push Docker Image
                  identifier: Push_Image
                  type: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: true
                    environmentVariables:
                      - name: DOCKERHUB_USERNAME
                        type: String
                        value: <+secrets.getValue("dockerhub-username")>
                      - name: DOCKERHUB_PASSWORD
                        type: String
                        value: <+secrets.getValue("dockerhub-password")>
                    source:
                      type: Inline
                      spec:
                        script: |
                          cd helloservice
                          echo """$DOCKERHUB_USERNAME"""
                          echo """$DOCKERHUB_PASSWORD"""
                          echo """$DOCKERHUB_PASSWORD""" | docker login -u """$DOCKERHUB_USERNAME""" --password-stdin
                          docker push $DOCKERHUB_USERNAME/helloservice:<+pipeline.sequenceId>
              - step:
                  name: Deploy to Kubernetes via SSH
                  identifier: Deploy_K8s
                  type: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "Deploying to Kubernetes via SSH..."

                          ssh -o StrictHostKeyChecking=no -i /home/harness/.ssh/test.pem ubuntu@13.201.60.197 "git clone https://github.com/DatlaBharath/helloservice-jenkins.git && cd helloservice-jenkins && helm install my-hello ./helm/helloservice"

                          rm -rf helloservice
