version: 2
plan:
    project-key: AUT
    name: Maven Build and Docker Deploy Plan
    key: MVN
triggers:
  - polling:
      period: '10'

stages:
  - Build and Deploy:
      jobs:
      - Build and Package

Build and Package:
    tasks:
    - script:
        - mvn clean install -DskipTests
        - docker build -t ${DOCKER_USER}/helloservice-jenkins:${bamboo.buildNumber} .
        - echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
        - docker push ${DOCKER_USER}/helloservice-jenkins:${bamboo.buildNumber}
        
    - script:
        - echo "Creating deployment.yaml"
        - |
            cat <<EOF > deployment.yaml
            apiVersion: apps/v1
            kind: Deployment
            metadata:
                name: helloservice-jenkins-deployment
            spec:
                replicas: 2
                selector:
                    matchLabels:
                      app: helloservice-jenkins
                template:
                    metadata:
                      labels:
                        app: helloservice-jenkins
                    spec:
                        containers:
                        - name: helloservice-jenkins
                          image: ${DOCKER_USER}/helloservice-jenkins:${bamboo.buildNumber}
                          ports:
                          - containerPort: 5000
            EOF
        
        - echo "Creating service.yaml"
        - |
            cat <<EOF > service.yaml
            apiVersion: v1
            kind: Service
            metadata:
                name: helloservice-jenkins-service
            spec:
                type: NodePort
                selector:
                  app: helloservice-jenkins
                ports:
                - port: 5000
                  targetPort: 5000
                  nodePort: 30007
            EOF
        
    - script:
        - echo "Deploying to Kubernetes"
        - rsync -e "ssh -o StrictHostKeyChecking=no -i /var/test.pem" -a deployment.yaml service.yaml ubuntu@13.127.208.46:/home/ubuntu/
        - ssh -o StrictHostKeyChecking=no -i /var/test.pem ubuntu@13.127.208.46 "kubectl apply -f /home/ubuntu/deployment.yaml && kubectl rollout status deployment/helloservice-jenkins-deployment || kubectl rollout undo deployment/helloservice-jenkins-deployment"
        - ssh -o StrictHostKeyChecking=no -i /var/test.pem ubuntu@13.127.208.46 "kubectl apply -f /home/ubuntu/service.yaml"