---
version: 2
plan:
    project-key: AUT
    name: Maven Build and s Docker Deploy Plan
    key: ABC

stages:
    - Build and Deploy:
        jobs:
        - Build and Package

Build and Package:
    tasks:
    - script:
        - echo $MyVar
