---
version: 2
plan:
    project-key: AUT
    name: Maven Build and Docker Deploy Plan
    key: JAV

stages:
    - Build and Deploy:
        jobs:
        - Build and Package

Build and Package:
    tasks:
    - script:
        description: "Build and Package Docker Image"
        - mvn clean install -DskipTests
        - docker build -t ${bamboo.dockerUser}/helloservice-jenkins:${bamboo.buildNumber} .
        - echo ${bamboo.dockerPass} | docker login -u ${bamboo.dockerUser} --password-stdin
        - docker push ${bamboo.dockerUser}/helloservice-jenkins:${bamboo.buildNumber}

    - script:
        description: "Create Kubernetes Deployment YAML"
        - echo "Creating deployment.yaml"
        - |
            cat <<EOF > deployment.yaml
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: helloservice-deployment
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: helloservice
              template:
                metadata:
                  labels:
                    app: helloservice
                spec:
                  containers:
                  - name: helloservice
                    image: ${bamboo.dockerUser}/helloservice-jenkins:${bamboo.buildNumber}
                    ports:
                    - containerPort: 5000
            EOF

    - script:
        description: "Create Kubernetes Service YAML"
        - echo "Creating service.yaml"
        - |
            cat <<EOF > service.yaml
            apiVersion: v1
            kind: Service
            metadata:
              name: helloservice-service
            spec:
              type: NodePort
              selector:
                app: helloservice
              ports:
              - port: 5000
                targetPort: 5000
                nodePort: 30007
            EOF

    - script:
        description: "Deploy to Kubernetes"
        - scp -o StrictHostKeyChecking=no -i /var/test.pem deployment.yaml service.yaml ubuntu@52.66.160.163:/home/ubuntu/
        - ssh -o StrictHostKeyChecking=no -i /var/test.pem ubuntu@52.66.160.163 "kubectl apply -f /home/ubuntu/deployment.yaml"
        - ssh -o StrictHostKeyChecking=no -i /var/test.pem ubuntu@52.66.160.163 "kubectl apply -f /home/ubuntu/service.yaml"