---
version: 2
plan:
  project-key: AUT
  name: Maven Build and Docker Deploy Plan
  key: ABC1

stages:
  - stage: Echo Variables
    jobs:
      - job: Echo Job
        tasks:
          - bash:
              script: |
                #!/bin/bash
                set -e
                
                echo "My Variable Value: $MyVar"
                echo "Full details of MyVar: ${bamboo.MyVar}"
