---
version: 2
plan:
  project-key: AUT
  name: Maven Build and Docker Deploy Plan
  key: ABC1

stages:
  - Echo Variables

pipeline:
  - stage: Echo Variables
    steps:
      - bash:
          script: |
            #!/bin/bash
            set -e
            
            echo "My Variable Value: $MyVar"
            echo "Full details of MyVar: ${bamboo.MyVar}"
