---
version: 2
plan:
    project-key: AUT
    name: Maven Build and Docker Deploy Plan
    key: ABC

stages:
    - Build and Deploy:
        jobs:
        - Build and Package

Build and Package:
    tasks:
    - script:
        script: |
            echo "MyVar value is: $MyVar"
