yaml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_project:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install -y maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

  build_image:
    runs-on: self-hosted
    needs: build_project
    steps:
      - name: Build Docker image
        run: docker build -t sakthisiddu1/helloservice-jenkins:${{ github.run_number }} .

  push_image:
    runs-on: self-hosted
    needs: build_image
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: docker push sakthisiddu1/helloservice-jenkins:${{ github.run_number }}

  deploy:
    runs-on: self-hosted
    needs: push_image
    steps:
      - name: Create Deployment and Service YAML files
        run: |
          echo "
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: helloservice-deployment
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: helloservice
            template:
              metadata:
                labels:
                  app: helloservice
              spec:
                containers:
                - name: helloservice
                  image: sakthisiddu1/helloservice-jenkins:${{ github.run_number }}
                  ports:
                  - containerPort: 5000
          " > deployment.yaml
          
          echo "
          apiVersion: v1
          kind: Service
          metadata:
            name: helloservice-service
          spec:
            type: NodePort
            ports:
            - nodePort: 30007
              port: 5000
              targetPort: 5000
            selector:
              app: helloservice
          " > service.yaml

      - name: Apply Kubernetes Configurations
        run: |
          ssh -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/test.pem ubuntu@3.6.238.137 "kubectl apply -f -" < deployment.yaml
          ssh -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/test.pem ubuntu@3.6.238.137 "kubectl apply -f -" < service.yaml